keys:
  - &admin age1j5fay5ac7xmzq0spnlnay4j6l80vrxmzphlgy4qszjjw62dr3prq0edl99
  - &server age12tsjfdpuajryjta6te8awr3l2ztq8rtynkr33st5kkdrp7me39mqg3west
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *admin
      - *server
